apiVersion: v1
kind: Service
metadata:
  name: deployment-nodeport-service
spec:
  type: NodePort 
  selector: 
    app: nginx-app-deploy
  ports: 
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31233

